version: '2'
services:
    oled:
        restart: always
        build: ./oled
        privileged: true
    motor:
        restart: always
        build: ./motor
        privileged: true
    camera:
        restart: always
        build: ./camera
        privileged: true
        ports:
            - "80:3000"
